apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: productpage-outside
  namespace: default
specs:
  - endpointSelector:
      matchLabels:
        "k8s:app": productpage
        "k8s:version": v1
    egress:
      - toEndpoints:
        - matchLabels:
            "k8s:app": reviews
            "k8s:version": v3
        toPorts:
        - ports:
          - port: "9080"
            protocol: TCP
          rules:
            http:
            - method: GET
              path: "/reviews/[0-9]*"
      - toEndpoints:
        - matchLabels:
            "k8s:app": details
            "k8s:version": v1
        toPorts:
        - ports:
          - port: "9080"
            protocol: TCP
          rules:
            http:
            - method: GET
              path: "/details/[0-9]*"
      - toEndpoints:
        toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"