apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: product-v1
  namespace: default
specs:
  - endpointSelector:
      matchLabels:
        "k8s:app": istio-ingressgateway
        "k8s:version": v1
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:app": productpage
      toPorts:
      - ports:
        - port: "9080"
          protocol: TCP
        rules:
          http:
          - method: GET
            path: "/details/[0-9]*"