apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: reviews-outside
  namespace: default
specs:
  - endpointSelector:
      matchLabels:
        "k8s:app": reviews
        "k8s:version": v3
    egress:
      - toEndpoints:
        - matchLabels:
            "k8s:app": ratings
            "k8s:version": v1
        toPorts:
        - ports:
          - port: "9080"
            protocol: TCP
          rules:
            http:
            - method: GET
              path: "/ratings/[0-9]*"
      - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
        toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"